name: Main

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --statistics --max-line-length=120 --select=E9,F63,F7,F82 --show-source
          flake8 . --count --statistics --max-line-length=120 --ignore=F40,F811 --exit-zero
  deploy:
    needs: lint
    runs-on: ubuntu-latest
    environment: c3kay-server
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          TARGET: ${{ secrets.TARGET }}
          SOURCE: "*.py"
          ARGS: "-auvz"
